POST http://localhost:3020/log-in
Content-type: application/json

{
    "username": "jinwei",
    "password":"Hello SIT323"
}
###
GET  http://localhost:3020/home-page
authorization: Bearere eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImppbndlaSIsImlhdCI6MTY3OTk4Mjk4NCwiZXhwIjoxNjc5OTgzMDg0fQ.cGj8TP_GEeFOIid_28qOABMroEmJOzRpyctGBIrxiRs


 
  